var Phaser = {
    "VERSION": {},
    "GAMES": function () {},
    "AUTO": {},
    "CANVAS": {},
    "WEBGL": {},
    "HEADLESS": {},
    "NONE": {},
    "LEFT": {},
    "RIGHT": {},
    "UP": {},
    "DOWN": {},
    "SPRITE": {},
    "BUTTON": {},
    "IMAGE": {},
    "GRAPHICS": {},
    "TEXT": {},
    "TILESPRITE": {},
    "BITMAPTEXT": {},
    "GROUP": {},
    "RENDERTEXTURE": {},
    "TILEMAP": {},
    "TILEMAPLAYER": {},
    "EMITTER": {},
    "POLYGON": {},
    "BITMAPDATA": {},
    "CANVAS_FILTER": {},
    "WEBGL_FILTER": {},
    "ELLIPSE": {},
    "SPRITEBATCH": {},
    "RETROFONT": {},
    "POINTER": {},
    "ROPE": {},
    "blendModes": {
        "NORMAL": {},
        "ADD": {},
        "MULTIPLY": {},
        "SCREEN": {},
        "OVERLAY": {},
        "DARKEN": {},
        "LIGHTEN": {},
        "COLOR_DODGE": {},
        "COLOR_BURN": {},
        "HARD_LIGHT": {},
        "SOFT_LIGHT": {},
        "DIFFERENCE": {},
        "EXCLUSION": {},
        "HUE": {},
        "SATURATION": {},
        "COLOR": {},
        "LUMINOSITY": {}
    },
    "scaleModes": {
        "DEFAULT": {},
        "LINEAR": {},
        "NEAREST": {}
    },
    "Utils": {
        "getProperty": function () {},
        "setProperty": function () {},
        "transposeArray": function () {},
        "rotateArray": function () {},
        "parseDimension": function () {},
        "shuffle": function () {},
        "pad": function () {},
        "isPlainObject": function () {},
        "extend": function () {},
        "mixin": function () {},
        "Debug": function () {}
    },
    "Circle": function () {},
    "Point": function () {},
    "Rectangle": function () {},
    "Line": function () {},
    "Ellipse": function () {},
    "Polygon": function () {},
    "Camera": function () {},
    "State": function () {},
    "StateManager": function () {},
    "LinkedList": function () {},
    "ArrayList": function () {},
    "Signal": function () {},
    "SignalBinding": function () {},
    "Filter": function () {},
    "Plugin": function () {},
    "PluginManager": function () {},
    "Stage": function () {},
    "Group": function () {},
    "World": function () {},
    "FlexGrid": function () {},
    "FlexLayer": function () {},
    "ScaleManager": function () {},
    "Game": function () {},
    "Input": function () {},
    "Key": function () {},
    "Keyboard": function () {},
    "Mouse": function () {},
    "MSPointer": function () {},
    "Pointer": function () {},
    "Touch": function () {},
    "Gamepad": function () {},
    "SinglePad": function () {},
    "GamepadButton": function () {},
    "InputHandler": function () {},
    "Events": function () {},
    "GameObjectFactory": function () {},
    "GameObjectCreator": function () {},
    "BitmapData": function () {},
    "Sprite": function () {},
    "Image": function () {},
    "TileSprite": function () {},
    "Rope": function () {},
    "Text": function () {},
    "BitmapText": function () {},
    "Button": function () {},
    "Graphics": function () {},
    "RenderTexture": function () {},
    "SpriteBatch": function () {},
    "RetroFont": function () {},
    "Particle": function () {},
    "Canvas": {
        "create": function () {},
        "getOffset": function () {},
        "getAspectRatio": function () {},
        "setBackgroundColor": function () {},
        "setTouchAction": function () {},
        "setUserSelect": function () {},
        "addToDOM": function () {},
        "removeFromDOM": function () {},
        "setTransform": function () {},
        "setSmoothingEnabled": function () {},
        "getSmoothingEnabled": function () {},
        "setImageRenderingCrisp": function () {},
        "setImageRenderingBicubic": function () {}
    },
    "Device": function () {},
    "RequestAnimationFrame": function () {},
    "Math": {
        "PI2": {},
        "fuzzyEqual": function () {},
        "fuzzyLessThan": function () {},
        "fuzzyGreaterThan": function () {},
        "fuzzyCeil": function () {},
        "fuzzyFloor": function () {},
        "average": function () {},
        "truncate": function () {},
        "shear": function () {},
        "snapTo": function () {},
        "snapToFloor": function () {},
        "snapToCeil": function () {},
        "snapToInArray": function () {},
        "roundTo": function () {},
        "floorTo": function () {},
        "ceilTo": function () {},
        "interpolateFloat": function () {},
        "angleBetween": function () {},
        "angleBetweenY": function () {},
        "angleBetweenPoints": function () {},
        "angleBetweenPointsY": function () {},
        "reverseAngle": function () {},
        "normalizeAngle": function () {},
        "normalizeLatitude": function () {},
        "normalizeLongitude": function () {},
        "chanceRoll": function () {},
        "numberArray": function () {},
        "numberArrayStep": function () {},
        "maxAdd": function () {},
        "minSub": function () {},
        "wrap": function () {},
        "wrapValue": function () {},
        "limitValue": function () {},
        "randomSign": function () {},
        "isOdd": function () {},
        "isEven": function () {},
        "min": function () {},
        "max": function () {},
        "minProperty": function () {},
        "maxProperty": function () {},
        "wrapAngle": function () {},
        "angleLimit": function () {},
        "linearInterpolation": function () {},
        "bezierInterpolation": function () {},
        "catmullRomInterpolation": function () {},
        "linear": function () {},
        "bernstein": function () {},
        "factorial": function () {},
        "catmullRom": function () {},
        "difference": function () {},
        "getRandom": function () {},
        "removeRandom": function () {},
        "floor": function () {},
        "ceil": function () {},
        "sinCosGenerator": function () {},
        "shift": function () {},
        "shuffleArray": function () {},
        "distance": function () {},
        "distancePow": function () {},
        "distanceRounded": function () {},
        "clamp": function () {},
        "clampBottom": function () {},
        "within": function () {},
        "mapLinear": function () {},
        "smoothstep": function () {},
        "smootherstep": function () {},
        "sign": function () {},
        "percent": function () {},
        "degToRad": function () {},
        "radToDeg": function () {}
    },
    "RandomDataGenerator": function () {},
    "QuadTree": function () {},
    "Net": function () {},
    "TweenManager": function () {},
    "Tween": function () {},
    "Easing": {
        "Linear": {
            "None": function () {}
        },
        "Quadratic": {
            "In": function () {},
            "Out": function () {},
            "InOut": function () {}
        },
        "Cubic": {
            "In": function () {},
            "Out": function () {},
            "InOut": function () {}
        },
        "Quartic": {
            "In": function () {},
            "Out": function () {},
            "InOut": function () {}
        },
        "Quintic": {
            "In": function () {},
            "Out": function () {},
            "InOut": function () {}
        },
        "Sinusoidal": {
            "In": function () {},
            "Out": function () {},
            "InOut": function () {}
        },
        "Exponential": {
            "In": function () {},
            "Out": function () {},
            "InOut": function () {}
        },
        "Circular": {
            "In": function () {},
            "Out": function () {},
            "InOut": function () {}
        },
        "Elastic": {
            "In": function () {},
            "Out": function () {},
            "InOut": function () {}
        },
        "Back": {
            "In": function () {},
            "Out": function () {},
            "InOut": function () {}
        },
        "Bounce": {
            "In": function () {},
            "Out": function () {},
            "InOut": function () {}
        },
        "Default": function () {}
    },
    "Time": function () {},
    "Timer": function () {},
    "TimerEvent": function () {},
    "AnimationManager": function () {},
    "Animation": function () {},
    "Frame": function () {},
    "FrameData": function () {},
    "AnimationParser": {
        "spriteSheet": function () {},
        "JSONData": function () {},
        "JSONDataHash": function () {},
        "XMLData": function () {}
    },
    "Cache": function () {},
    "Loader": function () {},
    "LoaderParser": {
        "bitmapFont": function () {}
    },
    "Sound": function () {},
    "SoundManager": function () {},
    "Color": {
        "packPixel": function () {},
        "unpackPixel": function () {},
        "fromRGBA": function () {},
        "toRGBA": function () {},
        "RGBtoHSL": function () {},
        "HSLtoRGB": function () {},
        "RGBtoHSV": function () {},
        "HSVtoRGB": function () {},
        "hueToColor": function () {},
        "createColor": function () {},
        "updateColor": function () {},
        "getColor32": function () {},
        "getColor": function () {},
        "RGBtoString": function () {},
        "hexToRGB": function () {},
        "hexToColor": function () {},
        "componentToHex": function () {},
        "HSVColorWheel": function () {},
        "HSLColorWheel": function () {},
        "interpolateColor": function () {},
        "interpolateColorWithRGB": function () {},
        "interpolateRGB": function () {},
        "getRandomColor": function () {},
        "getRGB": function () {},
        "getWebRGB": function () {},
        "getAlpha": function () {},
        "getAlphaFloat": function () {},
        "getRed": function () {},
        "getGreen": function () {},
        "getBlue": function () {}
    },
    "Physics": function () {},
    "Particles": function () {},
    "Tile": function () {},
    "Tilemap": function () {},
    "TilemapLayer": function () {},
    "TilemapParser": {
        "parse": function () {},
        "parseCSV": function () {},
        "getEmptyData": function () {},
        "parseTiledJSON": function () {}
    },
    "Tileset": function () {}
}
