var PIXI = {
    "WEBGL_RENDERER": {},
    "CANVAS_RENDERER": {},
    "VERSION": {},
    "blendModes": {
        "NORMAL": {},
        "ADD": {},
        "MULTIPLY": {},
        "SCREEN": {},
        "OVERLAY": {},
        "DARKEN": {},
        "LIGHTEN": {},
        "COLOR_DODGE": {},
        "COLOR_BURN": {},
        "HARD_LIGHT": {},
        "SOFT_LIGHT": {},
        "DIFFERENCE": {},
        "EXCLUSION": {},
        "HUE": {},
        "SATURATION": {},
        "COLOR": {},
        "LUMINOSITY": {}
    },
    "scaleModes": {
        "DEFAULT": {},
        "LINEAR": {},
        "NEAREST": {}
    },
    "_UID": {},
    "Float32Array": function () {},
    "Uint16Array": function () {},
    "INTERACTION_FREQUENCY": {},
    "AUTO_PREVENT_DEFAULT": {},
    "RAD_TO_DEG": {},
    "DEG_TO_RAD": {},
    "dontSayHello": {},
    "sayHello": function () {},
    "Matrix": function () {},
    "identityMatrix": {
        "a": {},
        "b": {},
        "c": {},
        "d": {},
        "tx": {},
        "ty": {},
        "fromArray": function () {},
        "toArray": function () {},
        "apply": function () {},
        "applyInverse": function () {}
    },
    "determineMatrixArrayType": function () {},
    "Matrix2": function () {},
    "DisplayObject": function () {},
    "DisplayObjectContainer": function () {},
    "Sprite": function () {},
    "SpriteBatch": function () {},
    "AbstractFilter": function () {},
    "FilterBlock": function () {},
    "Text": function () {},
    "BitmapText": function () {},
    "Stage": function () {},
    "hex2rgb": function () {},
    "rgb2hex": function () {},
    "AjaxRequest": function () {},
    "canUseNewCanvasBlendModes": function () {},
    "getNextPowerOfTwo": function () {},
    "EventTarget": function () {},
    "PolyK": {
        "Triangulate": function () {},
        "_PointInTriangle": function () {},
        "_convex": function () {}
    },
    "initDefaultShaders": function () {},
    "CompileVertexShader": function () {},
    "CompileFragmentShader": function () {},
    "_CompileShader": function () {},
    "compileProgram": function () {},
    "PixiShader": function () {},
    "PixiFastShader": function () {},
    "StripShader": function () {},
    "PrimitiveShader": function () {},
    "ComplexPrimitiveShader": function () {},
    "WebGLGraphics": function () {},
    "WebGLGraphicsData": function () {},
    "glContexts": function () {},
    "WebGLRenderer": function () {},
    "createWebGLTexture": function () {},
    "updateWebGLTexture": function () {},
    "WebGLBlendModeManager": function () {},
    "WebGLMaskManager": function () {},
    "WebGLStencilManager": function () {},
    "WebGLShaderManager": function () {},
    "WebGLSpriteBatch": function () {},
    "WebGLFastSpriteBatch": function () {},
    "WebGLFilterManager": function () {},
    "FilterTexture": function () {},
    "CanvasMaskManager": function () {},
    "CanvasTinter": function () {},
    "CanvasRenderer": function () {},
    "CanvasBuffer": function () {},
    "CanvasGraphics": function () {},
    "Graphics": function () {},
    "Strip": function () {},
    "Rope": function () {},
    "TilingSprite": function () {},
    "BaseTextureCache": function () {},
    "texturesToUpdate": function () {},
    "texturesToDestroy": function () {},
    "BaseTextureCacheIdGenerator": {},
    "BaseTexture": function () {},
    "TextureCache": function () {},
    "FrameCache": function () {},
    "TextureCacheIdGenerator": {},
    "Texture": function () {},
    "TextureUvs": function () {},
    "RenderTexture": function () {},
    "InteractionManager": function () {},
    "Circle": function () {},
    "Point": function () {},
    "Rectangle": function () {},
    "EmptyRectangle": {
        "x": {},
        "y": {},
        "width": {},
        "height": {},
        "offset": function () {},
        "offsetPoint": function () {},
        "setTo": function () {},
        "centerOn": function () {},
        "floor": function () {},
        "floorAll": function () {},
        "copyFrom": function () {},
        "copyTo": function () {},
        "inflate": function () {},
        "size": function () {},
        "clone": function () {},
        "contains": function () {},
        "containsRect": function () {},
        "equals": function () {},
        "intersection": function () {},
        "intersects": function () {},
        "intersectsRaw": function () {},
        "union": function () {},
        "toString": function () {},
        "constructor": function () {}
    },
    "Ellipse": function () {},
    "Polygon": function () {}
}
